---
apiVersion: batch/v1
kind: Job
metadata:
  name: ping
spec:
  template:
    spec:
      containers:
      - name: ping
        image: debian
        command: ["ping",  "8.8.8.8", "-c", "4"]
      restartPolicy: Never
  backoffLimit: 4

