kind: Service
apiVersion: v1
metadata:
  name: pi-solver-controller-service
spec:
  selector:
    app: pi-solver-controller
  type: NodePort
  ports:
  - name: pi-solver-controller
    protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 31766
