#!/bin/sh
read -p "Target Repo: " REPO
read -p "Version Number: " BUILDVERSION
export BUILDVERSION
export REPO
make -B
kubectl apply -f redis-service.yml
kubectl apply -f controller-service.yml
kubectl apply -f redis-deploy.yml
kubectl apply -f controller-deploy.yml
kubectl apply -f solver-deploy.yml


